Update 3-redirection

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -1,30 +1,32 @@
 #!/usr/bin/env bash
-# Installs, configures, and starts the server
-apt-get update
-apt-get -y install nginx
-sudo ufw allow 'Nginx HTTP'
-mkdir -p /var/www/html/
-sudo chmod -R 755 /var/www
-echo 'Hello World!' > /var/www/html/index.html
-SERVER_CONFIG=\
-"server {
-	listen 80 default_server;
-	listen [::]:80 default_server;
-	root /var/www/html;
-	index index.html index.htm index.nginx-debian.html;
-	server_name _;
-	location / {
-		try_files \$uri \$uri/ =404;
-	}
-	if (\$request_filename ~ redirect_me){
-		rewrite ^ https://sketchfab.com/bluepeno/models permanent;
-	}
-}"
+# Install and setup new nginx server
 
-bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
-
-if [ "$(pgrep -c nginx)" -le 0 ]; then
-	service nginx start
+apt-get update -y && \
+apt-get install -y nginx
+if [ $? -eq 0 ]
+then
+    service nginx start
+    echo -e \
+"http {
+    root /var/www/holberton;
+    server {
+        listen 80;
+        server_name pearmountain.space;
+        rewrite ^/redirect_me/? \
+https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
+        location / {
+            index index.html;
+        }
+    }
+}
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/holberton
+    echo "Holberton School" > \
+	/var/www/holberton/index.html
+    service nginx restart
 else
-	service nginx restart
+    echo "Could not install nginx"
+    exit 1
 fi
+exit 0
